// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	comModel "gfast/app/common/model"
	"gfast/app/system/dao/internal"
)

// sysPostDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type panorama1Dao struct {
	*internal.Panorama1Dao
}

var (
	// SysPost is globally public accessible object for table sys_post operations.
	Panorama1 panorama1Dao
)

func init() {
	Panorama1 = panorama1Dao{
		internal.NewPanorama1Dao(),
	}
}

// Fill with you ideas below.

// Panorama1SearchParams 搜索参数
type Panorama1SearchParams struct {
	// Panorama1Id int64 `p:"panorama1Id"`
	// Password string `p:"password"` //账号密码
	comModel.PageReq
}

// Panorama1AddParams 添加岗位参数
// type Panorama1AddParams struct {
// 	Username string `p:"username" v:"required#账号名称不能为空"`
// 	Password string `p:"password" v:"required#账号密码不能为空"`
// 	// PostSort  int    `p:"postSort" v:"required#岗位排序不能为空"`
// 	// Status    string `p:"status" v:"required#状态不能为空"`
// 	// Remark    string `p:"remark"`
// 	CreatedBy uint64
// }

// Panorama1EditParams 修改岗位参数
// type Panorama1EditParams struct {
// 	Panorama1Id int64 `p:"panorama1Id" v:"required#id必须"`
// 	Panorama1AddParams
// 	UpdatedBy uint64
// }
