// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	comModel "gfast/app/common/model"
	"gfast/app/system/dao/internal"
)

// sysPostDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type panoramaImgDao struct {
	*internal.PanoramaImgDao
}

var (
	// SysPost is globally public accessible object for table sys_post operations.
	PanoramaImg panoramaImgDao
)

func init() {
	PanoramaImg = panoramaImgDao{
		internal.NewPanoramaImgDao(),
	}
}

// Fill with you ideas below.

// PanoramaImgSearchParams 搜索参数
type PanoramaImgSearchParams struct {
	// PanoramaImgId int64 `p:"panoramaImgId"`
	// Password string `p:"password"` //账号密码
	comModel.PageReq
}

// PanoramaImgAddParams 添加岗位参数
type PanoramaImgAddParams struct {
	Picture string `p:"picture" v:"required#图片路径不能为空"`
	// PostSort  int    `p:"postSort" v:"required#岗位排序不能为空"`
	// Status    string `p:"status" v:"required#状态不能为空"`
	// Remark    string `p:"remark"`
	CreatedBy uint64
}

// PanoramaImgEditParams 修改岗位参数
// type PanoramaImgEditParams struct {
// 	PanoramaImgId int64 `p:"panoramaImgId" v:"required#id必须"`
// 	PanoramaImgAddParams
// 	UpdatedBy uint64
// }
