// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	comModel "gfast/app/common/model"
	"gfast/app/system/dao/internal"
)

// sysPostDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type sylasDao struct {
	*internal.SylasDao
}

var (
	// SysPost is globally public accessible object for table sys_post operations.
	Sylas sylasDao
)

func init() {
	Sylas = sylasDao{
		internal.NewSylasDao(),
	}
}

// Fill with you ideas below.

// SylasSearchParams 搜索参数
type SylasSearchParams struct {
	Username string `p:"username"` //账号名称
	Password string `p:"password"` //账号密码
	comModel.PageReq
}

// SylasAddParams 添加岗位参数
type SylasAddParams struct {
	Username  string `p:"username" v:"required#账号名称不能为空"`
	Password  string `p:"password" v:"required#账号密码不能为空"`
	// PostSort  int    `p:"postSort" v:"required#岗位排序不能为空"`
	// Status    string `p:"status" v:"required#状态不能为空"`
	// Remark    string `p:"remark"`
	CreatedBy uint64
}

// SylasEditParams 修改岗位参数
type SylasEditParams struct {
	SylasId int64 `p:"sylasId" v:"required#id必须"`
	SylasAddParams
	UpdatedBy uint64
}
