// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package model

import (
	// "github.com/gogf/gf/os/gtime"
)

// SysPost is the golang structure for table panorama1.
type Panorama1 struct {
	Panorama1Id     int64      `orm:"panorama1_id,primary" json:"panorama1Id"`    // panorama1ID
	Pcount  	    int64      `orm:"pcount"               json:"pcount"`  // 累计项目数
	HousesCount     int64      `orm:"houses_count"         json:"housesCount"`  // 累计房源数
	CurrentHouses   int64      `orm:"current_houses"       json:"currentHouses"`  // 当前持有房源数
	OperableHouses  int64      `orm:"operable_houses"      json:"operableHouses"`  // 可运营房源数
	RentalRate      int64      `orm:"rental_rate"          json:"rentalRate"`  // 出租率
	RentalPrice     int64      `orm:"rental_price"         json:"rentalPrice"`  // 出租均价
	ServiceEnt      int64      `orm:"service_ent"          json:"serviceEnt"`  // 累计服务企业数
	ServiceTenant   int64      `orm:"service_tenant"       json:"serviceTenant"`  // 累计服务租客数
	SmartDevices    int64      `orm:"smart_devices"        json:"smartDevices"`  // 接入智能设备数
	CooperativeOp   int64      `orm:"cooperative_op"       json:"cooperativeOp"`  // 合作运营商数
	AllianceEnt     int64      `orm:"alliance_ent"         json:"allianceEnt"`  // 入库联盟企业数
	// CreatedAt *gtime.Time `orm:"created_at"      json:"createdAt"` // 创建时间
	// UpdatedAt *gtime.Time `orm:"updated_at"      json:"updatedAt"` // 修改时间
	// DeletedAt *gtime.Time `orm:"deleted_at"      json:"deletedAt"` // 删除时间
}
