// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package model

import (
	// "github.com/gogf/gf/os/gtime"
)

// SysPost is the golang structure for table panoramaImg.
type PanoramaImg struct {
	PanoramaImgId   int64      `orm:"panoramaImg_id,primary" json:"panoramaImgId"`    // panoramaImgID
	Picture  	    string      `orm:"picture"               json:"picture"`  // 图片路径
	// CreatedAt *gtime.Time `orm:"created_at"      json:"createdAt"` // 创建时间
	// UpdatedAt *gtime.Time `orm:"updated_at"      json:"updatedAt"` // 修改时间
	// DeletedAt *gtime.Time `orm:"deleted_at"      json:"deletedAt"` // 删除时间
}
