// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package model

import (
	"github.com/gogf/gf/os/gtime"
)

// SysPost is the golang structure for table sylas.
type Sylas struct {
	SylasId    int64       `orm:"sylas_id,primary" json:"sylasId"`    // sylasID
	Username  string      `orm:"username"       json:"username"`  // 账号名称
	Password  string      `orm:"password"       json:"password"`  // 账号密码
	CreatedAt *gtime.Time `orm:"created_at"      json:"createdAt"` // 创建时间
	UpdatedAt *gtime.Time `orm:"updated_at"      json:"updatedAt"` // 修改时间
	DeletedAt *gtime.Time `orm:"deleted_at"      json:"deletedAt"` // 删除时间
}
